image:
  file: .gitpod.dockerfile

tasks:
  - init: ./mvnw clean install && ./front/yarn install
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - command: mvn spring-boot:run && ./front/yarn start